### ISSUE TITLE
Not able to get environment variables without .env file

### ISSUE THREAD

**Issue by sidv93** [mrsteele/dotenv-webpack#178]
Hi,

I'm trying to get environment variables already set in the system. I'm using docker-compose to set the environment varaibles. I believe setting "systemvars" to true should include variables from my current environment. But I'm getting a "failed to load ./.env" error.

Here is an example of my setup right now.

docker-compose.yml
```
services:
    web:
        restart: on-failure
        build:
            context: ./web
        env_file:
        -  .env
```     
This above code should set variables from the .env file to the container's environment.

webpack.config.js : 
```
const Dotenv = require('dotenv-webpack');

module.exports = (env) => {
    return {
            plugins: [
                new Dotenv({safe: false, systemvars: true})
            ]
    }
}
```

I believe "systemvars: true" should be set to true include existing environment variables.
I might be missing something simple, but any help is appreciated.

Thank you in advance.
